apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: minis-api
  name: minis-api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: minis-api
  type: LoadBalancer